config/routes.rb
RadiatorAPI::Application.routes.draw do
  get 'channels/import' => 'channels#import'
  post 'channels/import' => 'channels#importCreate'
  resources :channels

  get 'transmitters/import' => 'transmitters#import'
  post 'transmitters/import' => 'transmitters#importCreate'
  resources :transmitters

  get 'stations/import' => 'stations#import'
  get 'stations/:id/report' => 'stations#report'
  post 'stations/import' => 'stations#importCreate'
  resources :stations

  root 'stations#index'

end

app/models/transmitter.rb
class Transmitter < ActiveRecord::Base
  has_many :channels
end

app/controllers/transmitters_controller.rb
class TransmittersController < ApplicationController
  before_action :set_transmitter, only: [:show, :edit, :update, :destroy]

  # GET /transmitters
  # GET /transmitters.json
  def index

    respond_to do |format|
        format.html { @transmitters = Transmitter.all.paginate :page => params[:page] }
        format.json { @transmitters = Transmitter.all }
    end    
  end

  # GET /transmitters/1
  # GET /transmitters/1.json
  def show
  end
  
  # GET /transmitters/import
  def import
  end
  
  # POST /transmitters/import
  def importCreate
    params[:csv].split("|").each do |row|
      @array = row.split(";")
      @transmitter = Transmitter.new
      @transmitter.object = @array[0]
      @transmitter.city = @array[1]
      @transmitter.place = @array[2]
      @transmitter.longitude = @array[3]
      @transmitter.latitude = @array[4]
      @transmitter.save
    end
    
    
    render action: 'import'
  end

  # GET /transmitters/new
  def new
    @transmitter = Transmitter.new
  end

  # GET /transmitters/1/edit
  def edit
  end

  # POST /transmitters
  # POST /transmitters.json
  def create
    @transmitter = Transmitter.new(transmitter_params)

    respond_to do |format|
      if @transmitter.save
        format.html { redirect_to @transmitter, notice: 'Transmitter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @transmitter }
      else
        format.html { render action: 'new' }
        format.json { render json: @transmitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transmitters/1
  # PATCH/PUT /transmitters/1.json
  def update
    respond_to do |format|
      if @transmitter.update(transmitter_params)
        format.html { redirect_to @transmitter, notice: 'Transmitter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transmitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transmitters/1
  # DELETE /transmitters/1.json
  def destroy
    @transmitter.destroy
    respond_to do |format|
      format.html { redirect_to transmitters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transmitter
      @transmitter = Transmitter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transmitter_params
      params.require(:transmitter).permit(:object, :city, :place, :latitude, :longitude)
    end
end

app/helpers/transmitters_helper.rb
module TransmittersHelper
end

app/views/transmitters/_form.html.erb
<%= form_for(@transmitter) do |f| %>
  <% if @transmitter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transmitter.errors.count, "error") %> prohibited this transmitter from being saved:</h2>

      <ul>
      <% @transmitter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :object %><br>
    <%= f.text_field :object %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transmitters/_importForm.html.erb
<%= form_tag do %>
	<%= label_tag(:csv, "CSV:") %>
    <%= text_field_tag(:csv, params[:csv]) %>
    <%= submit_tag('Import', :name => nil) %>
<% end %>

app/views/transmitters/edit.html.erb
<h1>Editing transmitter</h1>

<%= render 'form' %>

<%= link_to 'Show', @transmitter %> |
<%= link_to 'Back', transmitters_path %>

app/views/transmitters/import.html.erb
<h1>Import transmitter</h1>

<%= render 'importForm' %>

<hr>
<%= @array %>
<hr>

<%= link_to 'Back', transmitters_path %>

app/views/transmitters/index.html.erb
<h1>Listing transmitters</h1>
<%= will_paginate @transmitters, renderer: BootstrapPagination::Rails %>

<table class="table table-striped table-bordered">

  <tbody>
    <% @transmitters.each do |transmitter| %>
      <tr>
          <td><%= link_to transmitter.city+", "+transmitter.object, transmitter %></td>
		  
        <td>
  		  <div class="btn-group">				  
  		  	<%= link_to '<i class="icon-edit icon-white"></i>'.html_safe, edit_transmitter_path(transmitter), method: :get, :class => 'btn btn-info' %>
  		  	<%= link_to '<i class="icon-remove icon-white"></i>'.html_safe, transmitter, method: :delete, :class => 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
  	  </div>
  </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @transmitters, renderer: BootstrapPagination::Rails %>

<%= link_to 'New Transmitter', new_transmitter_path %>

app/views/transmitters/new.html.erb
<h1>New transmitter</h1>

<%= render 'form' %>

<%= link_to 'Back', transmitters_path %>

app/views/transmitters/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @transmitter.place %></h1>

<img src="http://maps.googleapis.com/maps/api/staticmap?center=<%= @transmitter.longitude %>,<%= @transmitter.latitude %>&zoom=13&size=300x300&maptype=roadmap&scale=2&sensor=false" class="image-circle">

<hr>

<%= @transmitter.channels.count %> kanałów |
<%= link_to 'Edit', edit_transmitter_path(@transmitter) %> |
<%= link_to 'Back', transmitters_path %>