config/routes.rb
RadiatorAPI::Application.routes.draw do
  get 'channels/import' => 'channels#import'
  post 'channels/import' => 'channels#importCreate'
  resources :channels

  get 'transmitters/import' => 'transmitters#import'
  post 'transmitters/import' => 'transmitters#importCreate'
  resources :transmitters

  get 'stations/import' => 'stations#import'
  get 'stations/:id/report' => 'stations#report'
  post 'stations/import' => 'stations#importCreate'
  resources :stations

  root 'stations#index'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  
  belongs_to :transmitter
  belongs_to :station
  
  def hint
    @selfName = self.name.to_ascii.downcase
    Station.all.each do |station|
      @stationName = station.name.to_ascii.downcase
      if @selfName.include?(@stationName) || @stationName.include?(@selfName)
        return station.name
      end 
    end
    return nil
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    respond_to do |format|
        format.html { @channels = Channel.all.paginate :page => params[:page] }
        format.json { @channels = Channel.all }
    end
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
  end
  
  # GET /channels/import
  def import
    @transmitter = Transmitter.new
    @array = Array.new
  end
  
  # POST /transmitters/import
  def importCreate
    params[:csv].split("|").each do |row|
      @channel = Channel.new
      @array = row.split(";")
      @transmitter = Transmitter.where(:place => @array[0]).first
      @channel.transmitter = @transmitter
      @channel.name = @array[1]
      @channel.frequency = @array[2]
      @channel.power = @array[3]
      @channel.save
    end
    render action: 'import'
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
    @transmitter = @channel.transmitter
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render action: 'show', status: :created, location: @channel }
      else
        format.html { render action: 'new' }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:transmitter_id, :name, :frequency, :power)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_for(@channel) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% @channel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if Station.where(:name => @channel.name).count == 0 then %>
	  <% if @channel.hint %>
		  <div class="alert alert-info">
		    <button type="button" class="close" data-dismiss="alert">&times;</button>
		    <strong>Podpowiedź!</strong> Być może stacja, której szukasz to <%= @channel.hint %>?.
		  </div>
	  <% else%>
		  <div class="alert alert-error">
		    <button type="button" class="close" data-dismiss="alert">&times;</button>
		    <strong>Problem!</strong> Niestety nie mam dla Ciebie żadnej podpowiedzi.
		  </div>
	  <% end%>
<% else%>
		  <div class="alert alert-success">
		    <button type="button" class="close" data-dismiss="alert">&times;</button>
		    <strong>Super!</strong> Kanał jest sparowany ze stacją.
		  </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name%>
  </div>
  
  
  
  <div class="field">
    <%= f.label :frequency %><br>
    <%= f.text_field :frequency %>
  </div>
  <div class="field">
    <%= f.label :power %><br>
    <%= f.number_field :power %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/channels/_importForm.html.erb
<%= form_tag do %>
	<%= label_tag(:csv, "CSV:") %>
    <%= text_field_tag(:csv, params[:csv]) %>
    <%= submit_tag('Import', :name => nil) %>
<% end %>

app/views/channels/edit.html.erb
<div class="page-header">
  <h1>Editing channel <small><%= @channel.name %></small></h1>
</div>

<%= render 'form' %>

<div class="pagination">
  <ul>
    <li><%= link_to "Prev", edit_channel_path(Channel.find(params[:id].to_i-1)), method: :get %></li>
	 <li><%= link_to "Next", edit_channel_path(Channel.find(params[:id].to_i+1)), method: :get %></li>
  </ul>
</div>
<hr>
<h2><%= @transmitter.place %></h2>
<img src="http://maps.googleapis.com/maps/api/staticmap?center=Poland&markers=size:big%7Ccolor:green%7C<%= @transmitter.longitude %>,<%= @transmitter.latitude %>&zoom=5&size=300x300&maptype=roadmap&scale=1&sensor=false" class="image-circle">
<hr>
<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/import.html.erb
<h1>Import channel</h1>

<%= render 'importForm' %>

<hr>
<%= @array %>
<hr>

<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<h1>Listing channels</h1>
<%= will_paginate @channels, renderer: BootstrapPagination::Rails %>
<table class="table table-striped table-bordered">
    <tbody>
      <% @channels.each do |channel| %>
	  	<% if Station.where(:name => channel.name).count == 0 %>
    		<tr class="error">
	  	<% else %>
	      	<tr class="success">	
		<% end %>
	  
          <td><h4><%= channel.name %> <small>[<%= channel.frequency %> FM]</small></h4></td>
          <td><%= Transmitter.find(channel.transmitter_id).city %></td>
          <td>  
			  <div class="btn-group">				  
			  <%= link_to '<i class="icon-edit icon-white"></i>'.html_safe, edit_channel_path(channel), method: :get, :class => 'btn btn-info' %>
			  <%= link_to '<i class="icon-remove icon-white"></i>'.html_safe, channel, method: :delete, :class => 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
		  </div>
        </tr>
      <% end %>
    </tbody>

</table>

<%= will_paginate @channels, renderer: BootstrapPagination::Rails %>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form' %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>


<p>
  <strong>Transmitter:</strong>
  <%= @channel.transmitter_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @channel.name %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @channel.frequency %>
</p>

<p>
  <strong>Power:</strong>
  <%= @channel.power %>
</p>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>