config/routes.rb
RadiatorAPI::Application.routes.draw do
  get 'channels/import' => 'channels#import'
  post 'channels/import' => 'channels#importCreate'
  resources :channels

  get 'transmitters/import' => 'transmitters#import'
  post 'transmitters/import' => 'transmitters#importCreate'
  resources :transmitters

  get 'stations/import' => 'stations#import'
  get 'stations/:id/report' => 'stations#report'
  post 'stations/import' => 'stations#importCreate'
  resources :stations

  root 'stations#index'

end

app/models/station.rb
class Station < ActiveRecord::Base
  validates :name,        :presence => true
  validates :description, :presence => true
  validates :shortcut,    :presence => true
  validates :genre,       :presence => true
  validates :url,         :format => URI::regexp(%w(http)), :uniqueness => true
  
  has_many :channels
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    respond_to do |format|
        format.html { @stations = Station.all.paginate :page => params[:page] }
        format.json { @stations = Station.all }
    end
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end
  
  # GET /stations/import
  def import
    @station = Station.new
    @csv = String.new
    @array = Array.new
  end

  # POST /stations/import
  def importCreate
    @station = Station.new
    @csv = String.new
    @array = params[:csv].split(";")
    
    @station.name = @array[0]
    @station.url = @array[1]
    @station.description = @array[2]
    @station.shortcut = @array[3]
    @station.genre = @array[4]
    
    if @station.save
      redirect_to @station, notice: 'Station was successfully imported.'
    else
      render action: 'import'
    end
    
  end
  
  # GET /stations/new
  def new
    @station = Station.new
    @example = Station.all.shuffle.first
  end

  # GET /stations/1/edit
  def edit
    @example = @station
  end
  
  # GET /stations/1/report
  def report
    @station = Station.find(params[:id])
    ReportsMailer.report_mail(params[:id]).deliver
    redirect_to @station, notice: 'Station stream reported.'
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)
    @example = Station.all.shuffle.first

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render action: 'show', status: :created, location: @station }
      else
        format.html { render action: 'new' }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name, :description, :url, :genre, :shortcut)
    end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name %><br>
	<div class="controls">
	    <%= f.text_field :name, :placeholder => "np. "+@example.name %>
	</div>
  </div>
  <div class="field">
    <%= f.label :url.capitalize %><br>
    <%= f.text_field :url, :placeholder => "http://server.com/stream.mp3" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, :placeholder => "np. "+@example.description  %>
  </div>
  <div class="field">
    <%= f.label :shortcut %><br>
    <%= f.text_field :shortcut, :placeholder => "np. "+@example.shortcut  %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre, :placeholder => "music/talking/academic/regional/religion" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
  <% end %>

app/views/stations/edit.html.erb
<h1>Editing station</h1>

<%= render 'form' %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/import.html.erb
<h1>Import station</h1>

<%= render 'importForm' %>

<hr>
<%= @array %>
<hr>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<p>
	  <strong>Name:</strong>
	  <%= @station.name %>
	</p>
	<p>
	  <strong>Description:</strong>
	  <%= @station.description %>
	</p>
	<p>
	  <strong>Url:</strong>
	  <%= @station.url %>
	</p>
	<p>
	  <strong>Genre:</strong>
	  <%= @station.genre %>
	</p>
	<p>
	  <strong>Shortcut:</strong>
	  <%= @station.shortcut %>
	</p>
<hr>


<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<h1>Listing stations</h1>
 
<%= will_paginate @stations, renderer: BootstrapPagination::Rails %>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th></th>	
      <th>Name</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td>
			<%= image_tag(station.genre+".png", :alt => "music", :class => "genre img-rounded") %>
		</td>
        <td><%= link_to station.name, station %></td>
        <td><%= station.description %></td>
        <td>
		  <div class="btn-group">				  
		  	<%= link_to '<i class="icon-edit icon-white"></i>'.html_safe, edit_station_path(station), method: :get, :class => 'btn btn-info' %>
		  	<%= link_to '<i class="icon-remove icon-white"></i>'.html_safe, station, method: :delete, :class => 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
	  </div>
		</td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @stations, renderer: BootstrapPagination::Rails %>

<%= link_to 'New Station', new_station_path %>|
<%= link_to "Import Station", :action => "import" %>

app/views/stations/new.html.erb
<h1>New station</h1>
<hr>
<%= render 'form' %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @station.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @station.url %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @station.genre %>
</p>

<p>
  <strong>Shortcut:</strong>
  <%= @station.shortcut %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %> |
<%= link_to "New Station", :action => "new" %> |
<%= link_to "Import Station", :action => "import" %>